name: gameapp
description: GAMEAPP
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  easy_localization: ^3.0.3
  json_annotation: ^4.8.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  stacked: ^3.4.1+1
  timeago: ^3.5.0
  lottie: ^2.7.0
  flame: ^1.13.1
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  google_mobile_ads: ^4.0.0

  #benim paketler
  audioplayers: ^5.2.1
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  flame_lint: ^1.1.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
  - assets/lang/
  - assets/png/
  - assets/sounds/flp.mp3
  - assets/sounds/jump.mp3
  - assets/animation/
  - assets/font/
  - assets/images/
  - assets/images/boxes/

  fonts:
    - family: PixelFont
      fonts:
        - asset: assets/font/pixel.ttf
